language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
branches:
  only:
    - testing

env:
  - REDMINE_VERSION=2.3.2 VERBOSE=yes
  - REDMINE_VERSION=2.5.3 VERBOSE=yes
  - REDMINE_VERSION=2.6.1 VERBOSE=yes

script:
  - export PLUGIN=redmine_chatty_crow_notifications
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1
