# Model generated by scaffold
# Attributes
# user:references
# chatty_crow_channel:references
# contact:string

class ChattyCrowUserSetting < ActiveRecord::Base
  unloadable

  belongs_to :user
  belongs_to :chatty_crow_channel
  validates_presence_of :user, :chatty_crow_channel, :contact
end
