# Model generated by scaffold
# Attributes
# channel_type:string
# channel_token:string
# active:boolean

class ChattyCrowChannel < ActiveRecord::Base
  unloadable
  validates_presence_of :channel_type, :channel_token
  scope :active, lambda { where(active: true) }
  has_many :chatty_crow_user_settings, dependent: :destroy
end
